[theme]
primaryColor = "#0a0a0a"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#0a0a0a"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true




